config/routes.rb
Rails.application.routes.draw do

  resources :playlists #except: [:new, :create]
  resources :songs
  resources :playlist_songs

  root  'static_pages#home'
  match '/about',   to: 'static_pages#about',     via: 'get'
  match '/contact', to: 'static_pages#contact',   via: 'get'
  match '/privacy', to: 'static_pages#privacy',   via: 'get'
  match '/terms',   to: 'static_pages#terms',     via: 'get'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup',  to: 'users#new',              via: 'get'
  match '/signin',  to: 'sessions#new',           via: 'get'
  match '/signout', to: 'sessions#destroy',       via: 'delete'

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  has_many :songs
  belongs_to :user
  default_scope -> { order('created_at DESC') }
  validates :name, presence: { case_sensitive: false }, length: { maximum: 50 }
  validates :keycode, length: { maximum: 20 }
  validates :user_id, presence: true
end

app/models/playlist_song.rb
class PlaylistSong < ActiveRecord::Base
  belongs_to :song
  belongs_to :playlist

  validates :song_id, presence: true
  validates :playlist_id, presence: true 
end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :user
  belongs_to :playlist
  validates :title, presence: true, uniqueness: { case_sensitive: false }
  validates :artist, presence: true
  validates :user_id, presence: true
  validates :path, presence: true
  validates :playlist_id, presence: true
  mount_uploader :path, SongUploader
end

app/models/user.rb
class User < ActiveRecord::Base

  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates :username, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, length: { minimum: 6 }

  has_many :playlists, dependent: :destroy
  has_many :songs, dependent: :destroy

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  def create_remember_token
    self.remember_token = User.digest(User.new_remember_token)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/playlist_songs_controller.rb
class PlaylistSongsController < ApplicationController
  def new
  end

  def create
  end

  def destroy
  end

  def edit
  end

  def update
  end

  def show
  end

  def index
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController

  before_action :signed_in_user, only: [:index, :create,]
  before_action :correct_user,   only: :destroy

  def new
    @playlist = Playlist.new
  end

  def create
    @playlist = current_user.playlists.build(playlist_params)
    if @playlist.save
      flash[:success] = "Playlist created!"
      redirect_to playlist_path(@playlist.id)
    else
      render :new
    end
  end

  def show
    @playlist = Playlist.find(params[:id])
  end

  def index
    @playlists = Playlist.paginate(page: params[:page])
  end

  def edit
    @playlist = Playlist.find(params[:id])
  end

  def update
  end

  def destroy
    @playlist.destroy
    flash[:success] = "Playlist deleted."
    redirect_to @playlist.user
  end

  private

  def playlist_params
    params.require(:playlist).permit(:name)
  end

  # Before filters

  def correct_user
      @playlist = current_user.playlists.find(params[:id])
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  before_action :correct_user,   only: :destroy

  def new
    @song = Song.new
    @playlist = Playlist.find(params[:playlist_id])
  end

  def create
    @song = current_user.songs.build(song_params)
    if @song.save
      flash[:success] = "Track added!"
      redirect_to playlist_path(@song.playlist_id)
    else
      render :new
    end
  end

  def destroy
    @song.destroy
    flash[:success] = "Track deleted"
    redirect_to @song.playlist
  end

  private

  def song_params
    params.require(:song).permit(:title, :artist, :path, :playlist_id)
  end

  # Before filters

  def correct_user
    @song = current_user.songs.find(params[:id])
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

  def about
  end

  def contact
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :signed_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Profile Created"
      sign_in @user
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @playlists = @user.playlists.paginate(page: params[:page])
  end

  def index
    @users = User.paginate(page: params[:page])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile Updated"
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to users_url
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  # Before filters

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title)
    base_title = "PUSHPOP"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

end

app/helpers/playlist_songs_helper.rb
module PlaylistSongsHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def sign_out
    current_user.update_attribute(:remember_token, User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end

end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=60"
    image_tag(gravatar_url, alt: user.username, class: "gravatar")
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/partials/shim' %>
  </head>
  <body>
    <%= render 'layouts/partials/header' %>
    <div class="container">
      <div class="center hero-unit">
        <%= yield %>
      </div>
      <%= render 'layouts/partials/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/layouts/partials/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Privacy", privacy_path %></li>
      <li><%= link_to "Terms", terms_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/partials/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "PUSHPOP", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">

          <% if signed_in? %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Menu <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Create Playlist", new_playlist_path %></li>
                <li><%= link_to "Search Playlists", playlists_path %></li>
                <li><%= link_to "Search Users", users_path %></li>
                <li><%= link_to "Profile", current_user %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign Out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Menu <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Search Playlists", playlists_path %></li>
                <li><%= link_to "Search Users", users_path %></li>
                <li class="divider"></li>
                <li><%= link_to "Sign In", signin_path, id: "sign_in" %></li>
                <li><%= link_to "Sign Up", signup_path %></li>
              </ul>
          <% end %>

        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/partials/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/partials/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" class="alert alert-error">
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/playlists/create.html.erb
<h1>Playlists#create</h1>
<p>Find me in app/views/playlists/create.html.erb</p>

app/views/playlists/destroy.html.erb
<h1>Playlists#destroy</h1>
<p>Find me in app/views/playlists/destroy.html.erb</p>

app/views/playlists/edit.html.erb
<h1>Playlists#edit</h1>
<p>Find me in app/views/playlists/edit.html.erb</p>

app/views/playlists/index.html.erb
<h1>Playlist Index</h1>

<%= will_paginate @playlists%>

<ul class="users">
  <% @playlists.each do |list| %>
    <li class="every">
      <%= link_to list.user.username, list.user %>
      <span>Added:  </span>
      <%= link_to list.name, list %>
      <% if current_user.admin? && !current_user?(user) %>
        |  <%= link_to "delete", list, method: :delete, data: { confirm: "You sure?" } %>
      <% end %>
    </li>
  <% end %>
</ul>

<%= will_paginate @playlists%>

app/views/playlists/new.html.erb
<% provide(:title, 'New Playlist') %>
<h1>Create A New Playlist</h1>

<div class="row">
  <section>
    <%= form_for(@playlist) do |f| %>
      <%= render 'layouts/partials/shared/error_messages', object: f.object %>
      <%= f.text_field :name, placeholder: "Playlist name" %>
      <!-- <%= f.text_field :keycode, placeholder: "Playlist keycode (optional)" %> -->
      <h3>You can upload songs after creation.</h3>
      <%= f.submit "Create Playlist", class: "btn btn-large btn-primary" %>
    <% end %>
  </section>
</div>

app/views/playlists/show.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>
<h2><%= link_to @playlist.user.username, @playlist.user %></h2>
<h1><%= @playlist.name %></h1>

<%= link_to "Add A Track", new_song_path(:playlist_id => @playlist.id), class: "btn btn-large btn-primary" %>

<% if @playlist.songs.any? %>
  <audio id="audio" preload="auto" tabindex="0" controls="" ></audio>
  <h3>Tracks (<%= @playlist.songs.count %>)</h3>
  <ul class="playlists" id="playlist">
    <% @playlist.songs.each do |song| %>
      <li class="active every">
        <span class="playlist"><%= link_to song.user.username, song.user %> added:</span>
        <span class="timestamp">
          <a class="track" href="<%= song.path %>"><%= song.title %></a> by: <%= song.artist %>
        </span>
        <% if current_user?(song.playlist.user) || current_user?(song.user) %>
          <span>  ||  </span>
          <%= link_to "delete", song, method: :delete, data: { confirm: "You sure?" }, title: song.title %>
        <% end %><br>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/playlists/update.html.erb
<h1>Playlists#update</h1>
<p>Find me in app/views/playlists/update.html.erb</p>

app/views/songs/create.html.erb
<h1>Songs#create</h1>
<p>Find me in app/views/songs/create.html.erb</p>

app/views/songs/destroy.html.erb
<h1>Songs#destroy</h1>
<p>Find me in app/views/songs/destroy.html.erb</p>

app/views/songs/new.html.erb
<h3>Add a track to <%= @playlist.name %></h3>

<div class="row">
  <%= form_for(@song, :multipart => true) do |f| %>
    <%= render 'layouts/partials/shared/error_messages', object: f.object %>
    <%= f.text_field :title, placeholder: "Title" %>
    <%= f.text_field :artist, placeholder: "Artist" %>
    <%= f.hidden_field :playlist_id, :value => params[:playlist_id] %>
    <%= f.file_field :path %>
    <%= f.submit "Add your track", class: "btn btn-large btn-primary" %>
  <% end %>
</div>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About PUSHPOP</h1>
<h2>
  This is the About Page for the
  <a href="https://pushpop-nss.herokuapp.com/">PUSHPOP</a>
  application.
</h2><br>
<h3>Content is forthcoming.</h3>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact Us</h1><br>
<h2>Spencer Forrest Anastasio</h2><br>
<h3>anastasio.spencer@gmail.com</h3><br>
<h3>(281) 787-8388</h3>

app/views/static_pages/home.html.erb
<h1>PUSHPOP</h1>
<% if signed_in? %>
  <div class="row">
  </div>
<% else %>
  <h3><%= link_to "Sign In", signin_path %></h3>
  <h2>Or</h2>
  <h3><%= link_to "Sign Up", signup_path %></h3>
<% end %>

app/views/static_pages/privacy.html.erb
<% provide(:title, 'Privacy') %>
<h1>Privacy Policy</h1>

<p>Last updated: June 15, 2014</p>

<p>PUSHPOP ("us", "we", or "our") operates the http://pushpop-nss.herokuapp.com/ website (the "Service").</p>

<p>This page informs you of our policies regarding the collection, use and disclosure of Personal Information when you use our Service.</p>

<p>We will not use or share your information with anyone except as described in this Privacy Policy.</p>

<p>We use your Personal Information for providing and improving the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, accessible at http://pushpop-nss.herokuapp.com/</p>

<p><strong>Information Collection And Use</strong></p>

<p>While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you. Personally identifiable information may include, but is not limited to, your name ("Personal Information").</p>

<p><strong>Log Data</strong></p>

<p>We collect information that your browser sends whenever you visit our Service ("Log Data"). This Log Data may include information such as your computer's Internet Protocol ("IP") address, browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages and other statistics.</p>

<p><strong>Cookies</strong></p>

<p>Cookies are files with small amount of data, which may include an anonymous unique identifier. Cookies are sent to your browser from a web site and stored on your computer's hard drive.</p>

<p>We use "cookies" to collect information. You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.</p>

<p><strong>Service Providers</strong></p>

<p>We may employ third party companies and individuals to facilitate our Service, to provide the Service on our behalf, to perform Service-related services or to assist us in analyzing how our Service is used.</p>

<p>These third parties have access to your Personal Information only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</p>

<p><strong>Security</strong></p>

<p>The security of your Personal Information is important to us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Information, we cannot guarantee its absolute security.</p>

<p><strong>Links To Other Sites</strong></p>

<p>Our Service may contain links to other sites that are not operated by us. If you click on a third party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.</p>

<p>We have no control over, and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>

<p><strong>Children's Privacy</strong></p>

<p>Our Service does not address anyone under the age of 13 ("Children").</p>

<p>We do not knowingly collect personally identifiable information from children under 13. If you are a parent or guardian and you are aware that your Children has provided us with Personal Information, please contact us. If we discover that a Children under 13 has provided us with Personal Information, we will delete such information from our servers immediately.</p>

<p><strong>Changes To This Privacy Policy</strong></p>

<p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</p>

<p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>

<p>Generated with permission from <a href="http://termsfeed.com/" title="TermsFeed" style="color: #999; text-decoration: none;">TermsFeed</a></p>

<p><strong>Contact Us</strong></p>

<p>If you have any questions about this Privacy Policy, please contact us.</p>

app/views/static_pages/terms.html.erb
<% provide(:title, 'Terms') %>
<h1>PUSHPOP Terms of Service ("Agreement")</h1>
<p>This Agreement was last modified on June 15, 2014.</p>

<p>Please read these Terms of Service ("Agreement", "Terms of Service") carefully before using http://pushpop-nss.herokuapp.com/ ("the Site") operated by PUSHPOP ("us", "we", or "our"). This Agreement sets forth the legally binding terms and conditions for your use of the Site at http://pushpop-nss.herokuapp.com/.</p>
<p>By accessing or using the Site in any manner, including, but not limited to, visiting or browsing the Site or contributing content or other materials to the Site, you agree to be bound by these Terms of Service. Capitalized terms are defined in this Agreement.</p>

<p><strong>Intellectual Property</strong><br />The Site and its original content, features and functionality are owned by PUSHPOP and are protected by international copyright, trademark, patent, trade secret and other intellectual property or proprietary rights laws.</p>

<p><strong>Termination</strong><br />We may terminate your access to the Site, without cause or notice, which may result in the forfeiture and destruction of all information associated with you. All provisions of this Agreement that by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity, and limitations of liability.</p>

<p><strong>Links To Other Sites</strong><br />Our Site may contain links to third-party sites that are not owned or controlled by PUSHPOP.</p>
<p>PUSHPOP has no control over, and assumes no responsibility for, the content, privacy policies, or practices of any third party sites or services. We strongly advise you to read the terms and conditions and privacy policy of any third-party site that you visit.</p>

<p><strong>Governing Law</strong><br />This Agreement (and any further rules, policies, or guidelines incorporated by reference) shall be governed and construed in accordance with the laws of Tennessee, United States, without giving effect to any principles of conflicts of law.</p>

<p><strong>Changes To This Agreement</strong><br />We reserve the right, at our sole discretion, to modify or replace these Terms of Service by posting the updated terms on the Site. Your continued use of the Site after any such changes constitutes your acceptance of the new Terms of Service.</p>
<p>Please review this Agreement periodically for changes. If you do not agree to any of this Agreement or any changes to this Agreement, do not use, access or continue to access the Site or discontinue any use of the Site immediately.</p>

<p><strong>Contact Us</strong><br />If you have any questions about this Agreement, please contact us.</p>

<p style="font-size: 85%; color: #999;">From <a href="http://termsfeed.com" title="TermsFeed" style="color: #999; text-decoration: none;" rel="nofollow">TermsFeed Generator</a>.</p>

app/views/users/edit.html.erb
<% provide(:title, "Edit Profile") %>
<h1>Update Your Profile</h1>

<div class="row">
  <%= form_for(@user) do |f| %>
    <%= render 'layouts/partials/shared/error_messages', object: f.object %>
    <div class="grav field">
      <a href="http://gravatar.com/emails"><%= gravatar_for @user %></a><br>
      <%= f.text_field :username, placeholder: "Username" %>
      <%= f.text_field :email, placeholder: "Email (with Gravatar)" %>
      <%= f.password_field :password, placeholder: "Password" %>
      <%= f.password_field :password_confirmation, placeholder: "Password Confirmation" %>
      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<% provide(:title, 'Users') %>
<h1>User Index</h1>

<%= will_paginate %>

<ul class="users">
  <% @users.each do |user| %>
    <li class="every">
      <h2><%= gravatar_for user %>
      <%= link_to user.username, user %></h2>
      <% if current_user.admin? && !current_user?(user) %>
        ||  <%= link_to "delete", user, method: :delete, data: { confirm: "You sure?" } %>
      <% end %>
    </li>
  <% end %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>
<h1>Sign Up</h1>

<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

<div class="row">
  <%= form_for(@user) do |f| %>
    <%= render 'layouts/partials/shared/error_messages', object: f.object %>
    <%= f.text_field :username, placeholder: "Username" %>
    <%= f.text_field :email, placeholder: "Email (with Gravatar)" %>
    <%= f.password_field :password, placeholder: "Password" %>
    <%= f.password_field :password_confirmation, placeholder: "Password Confirmation" %>
    <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
  <% end %>
  <p>Already registered? <%= link_to "Sign in now!", signin_path %></p>
</div>

app/views/users/show.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

<% provide(:title, @user.username) %>
<div class="row">
  <section>
    <ul id="profile">
      <li><%= gravatar_for @user %></li>
      <li><h2><%= @user.username %></h2></li>
      <% if current_user?(@user) %>
        <li><p><%= link_to "Create Playlist", new_playlist_path %></p></li>
        <li><p><%= link_to "Edit Profile", edit_user_path(current_user) %></p></li>
      <% end %>
    </ul>
    <% if @user.playlists.any? %>
      <h3>Playlists (<%= @user.playlists.count %>)</h3>
      <div class="center">
        <%= will_paginate @playlists %>
        <ol class="playlists">
          <% @user.playlists.each do |list| %>
            <li class="every">
              <span class="playlist"><%= link_to list.name, list %></span>
              <% if current_user?(list.user) %>
                <span>  ||  </span>
                <%= link_to "delete", list, method: :delete, data: { confirm: "You sure?" }, title: list.name %>
              <% end %>
            </li>
          <% end %>
        </ol>
        <%= will_paginate @playlists %>
      </div>
    <% end %>
  </section>
</div>